from enum import Enum


class AdvertStatus(Enum):
    DELETING_IN_PROGRESS = -1
    READY_TO_LAUNCH = 4
    CAMPAIGN_COMPLETED = 7
    DECLINED = 8
    SHOWING_IN_PROGRESS = 9
    PAUSED = 11


class AdvertType(Enum):
    LEGACY_CATALOG = 4
    LEGACY_PRODUCT_CARD = 5
    LEGACY_SEARCH = 6
    LEGACY_HOME_RECOMMENDATIONS = 7
    AUTOMATIC_CAMPAIGN = 8
    AUCTION = 9
