[project]
name = "pywbmodels"
version = "0.1.0"
description = "Python Wildberries Seller API Models"
requires-python = ">=3.12"
dependencies = [
    "adaptix>=3.0.0b10",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
